backend:
  name: github
  repo: ct-unn-a/unn-a-site # Altera para o teu user/repo do GitHub
  branch: main
  # Usamos este gateway gratuito da comunidade para fazer a ponte de login:
  base_url: https://oauth.staticcms.org
  auth_endpoint: /api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projetos"
    label: "Projetos"
    label_singular: "Projeto"
    file: "projetos.json"
    format: "json"
    editor:
      preview: false
    fields:
      - label: "Lista de Projetos"
        name: "projetos"
        widget: "object"
        fields:
          - { label: "Título em PT", name: "titlePT", widget: "string" }
          - { label: "Título em EN", name: "titleEN", widget: "string" }
          - { label: "Meta Detalhes PT", name: "metaPT", widget: "string" }
          - { label: "Meta Detalhes EN", name: "metaEN", widget: "string" }
          - { label: "Descrição", name: "description", widget: "text" }
          - { label: "Galeria de Imagens", name: "images", widget: "list", field: { label: "Imagem", name: "image", widget: "image" } }
