backend:
  name: github
  repo: ct-unn-a/unn-a-site
  branch: main
  # Alterado para o novo servidor estável:
  base_url: https://decap-cms-oauth-node.vercel.app
  auth_endpoint: /api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "dados"
    label: "Dados do Site"
    # Quando queremos editar ficheiros JSON específicos, usamos 'files' desta forma:
    files:
      - name: "lista_projetos"
        label: "Projetos UNN-A"
        file: "projetos.json"
        format: "json"
        editor:
          preview: false
        fields:
          - label: "Lista de Projetos"
            name: "projetos"
            widget: "object"
            fields:
              # Isto mapeia diretamente para o interior do teu projetos.json
              - { label: "Título em PT", name: "titlePT", widget: "string" }
              - { label: "Título em EN", name: "titleEN", widget: "string" }
              - { label: "Meta Detalhes PT", name: "metaPT", widget: "string" }
              - { label: "Meta Detalhes EN", name: "metaEN", widget: "string" }
              - { label: "Descrição", name: "description", widget: "text" }
              - { label: "Galeria de Imagens", name: "images", widget: "list", field: { label: "Imagem", name: "image", widget: "image" } }
